name: laminario_virtual_mobile
description: Implementação do laminário virtual da UFCSPA em Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/Logo.png

  #Imagens do tecido conjuntivo
  - images/laminas/tecidoconjuntivo/cartilaginoso_hialino/x100.jpg
  - images/laminas/tecidoconjuntivo/cartilaginoso_hialino/x400.jpg
  - images/laminas/tecidoconjuntivo/cartilaginoso_hialino/capa.jpg
  - images/laminas/tecidoconjuntivo/tecido_sanguineo/x40.jpg
  - images/laminas/tecidoconjuntivo/tecido_sanguineo/x100.jpg
  - images/laminas/tecidoconjuntivo/tecido_sanguineo/x200.jpg
  - images/laminas/tecidoconjuntivo/tecido_sanguineo/x400.jpg
  - images/laminas/tecidoconjuntivo/tecido_sanguineo/capa.jpg
  #Imagens do tecido epitelial
  - images/laminas/tecidoepitelial/glandular_exocrino_acinoso_de_secreção_holocrina/x200.jpg
  - images/laminas/tecidoepitelial/glandular_exocrino_acinoso_de_secreção_holocrina/x400.jpg
  - images/laminas/tecidoepitelial/glandular_exocrino_acinoso_de_secreção_holocrina/capa.jpg
  - images/laminas/tecidoepitelial/glandular_exocrino_tubular_espiralado_simples/x40.jpg
  - images/laminas/tecidoepitelial/glandular_exocrino_tubular_espiralado_simples/capa.jpg
  #Imagens do tecido muscular
  - images/laminas/tecidomuscular/estriado_esqueletico/x400.jpg
  - images/laminas/tecidomuscular/estriado_esqueletico/capa.jpg
  - images/laminas/tecidomuscular/liso/x400.jpg
  - images/laminas/tecidomuscular/liso/capa.jpg
  #Imagens do tecido nervoso
  - images/laminas/tecidonervoso/cerebelo/x40.jpg
  - images/laminas/tecidonervoso/cerebelo/x100.jpg
  - images/laminas/tecidonervoso/cerebelo/x400.jpg
  - images/laminas/tecidonervoso/cerebelo/capa.jpg
  - images/laminas/tecidonervoso/medula_espinhal/x40.jpg
  - images/laminas/tecidonervoso/medula_espinhal/x100.jpg
  - images/laminas/tecidonervoso/medula_espinhal/x400.jpg
  - images/laminas/tecidonervoso/medula_espinhal/capa.jpg
  #Imagens do sistema cardiovascular
  - images/laminas/sistemacardiovascular/aorta/x40.jpg
  - images/laminas/sistemacardiovascular/aorta/capa.jpg
  - images/laminas/sistemacardiovascular/veia_media_e_aorta_media/x40.jpg
  - images/laminas/sistemacardiovascular/veia_media_e_aorta_media/x200.jpg
  - images/laminas/sistemacardiovascular/veia_media_e_aorta_media/capa.jpg
  #Imagens do sistema reprodutor feminino
  - images/laminas/sistemareprodutorfeminino/tuba_uterina/capa.jpg
  - images/laminas/sistemareprodutorfeminino/tuba_uterina/x40.jpg
  - images/laminas/sistemareprodutorfeminino/tuba_uterina/x100.jpg
  - images/laminas/sistemareprodutorfeminino/tuba_uterina/x400.jpg
  - images/laminas/sistemareprodutorfeminino/utero/capa.jpg
  - images/laminas/sistemareprodutorfeminino/utero/x40.jpg
  - images/laminas/sistemareprodutorfeminino/utero/x100.jpg
  - images/laminas/sistemareprodutorfeminino/utero/x200.jpg
  - images/laminas/sistemareprodutorfeminino/utero/x400.jpg
  #Imagens do Sistema Reprodutor Masculino
  - images/laminas/sistemareprodutormasculino/prostata/capa.jpg
  - images/laminas/sistemareprodutormasculino/prostata/x40.jpg
  - images/laminas/sistemareprodutormasculino/prostata/x100.jpg
  - images/laminas/sistemareprodutormasculino/prostata/x200.jpg
  - images/laminas/sistemareprodutormasculino/prostata/x400.jpg
  - images/laminas/sistemareprodutormasculino/testiculo/capa.jpg
  - images/laminas/sistemareprodutormasculino/testiculo/x40.jpg
  - images/laminas/sistemareprodutormasculino/testiculo/x100.jpg
  - images/laminas/sistemareprodutormasculino/testiculo/x200.jpg
  - images/laminas/sistemareprodutormasculino/testiculo/x400.jpg
  - #Imagens do Sistema Respiratório
  - images/laminas/sistemarespiratorio/pulmao/capa.jpg
  - images/laminas/sistemarespiratorio/pulmao/x40.jpg
  - images/laminas/sistemarespiratorio/pulmao/x100.jpg
  - images/laminas/sistemarespiratorio/pulmao/x200.jpg
  - images/laminas/sistemarespiratorio/pulmao/x400.jpg
  - images/laminas/sistemarespiratorio/traqueia/capa.jpg
  - images/laminas/sistemarespiratorio/traqueia/x40.jpg
  - images/laminas/sistemarespiratorio/traqueia/x100.jpg
  - images/laminas/sistemarespiratorio/traqueia/x400.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
